# Generated by Django 5.0.1 on 2024-01-21 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente_producto_vendedores_remove_curso_profesor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campera',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.producto')),
                ('talle', models.CharField(max_length=10)),
                ('material', models.CharField(max_length=20)),
                ('pais_fabricante', models.CharField(max_length=30)),
            ],
            bases=('core.producto',),
        ),
        migrations.CreateModel(
            name='Gorra',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.producto')),
                ('talle', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=20)),
                ('pais_fabricante', models.CharField(max_length=30)),
            ],
            bases=('core.producto',),
        ),
        migrations.CreateModel(
            name='Jean',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.producto')),
                ('talle', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=20)),
                ('material', models.CharField(max_length=20)),
            ],
            bases=('core.producto',),
        ),
        migrations.CreateModel(
            name='Zapatilla',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.producto')),
                ('talle', models.CharField(max_length=10)),
                ('pais_fabricante', models.CharField(max_length=30)),
            ],
            bases=('core.producto',),
        ),
    ]
