# Generated by Django 5.0.1 on 2024-01-21 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_campera_gorra_jean_zapatilla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='comprador',
        ),
        migrations.DeleteModel(
            name='Vendedores',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='articulo',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
